### ISSUE TITLE
Notebook is not loading

### ISSUE THREAD

**Issue by bairo** [llSourcell/How-to-Build-a-Biomedical-Startup#2]
![image](https://user-images.githubusercontent.com/3649124/60033458-31432900-96db-11e9-8a10-ebe7c4078417.png)

**Comment by eagerashwani** [comment]
https://colab.research.google.com/drive/1Rz2rzkwWrVEXcjiQqTXhxzLCW5cXi7xA

If you still got error, checkout your browser settings

**Comment by bairo** [comment]
> https://colab.research.google.com/drive/1Rz2rzkwWrVEXcjiQqTXhxzLCW5cXi7xA
> 
> If you still got error, checkout your browser settings

you are right, it was due to the BRAVE browser. Worked fine in chrome.

thanks
